= Страница в разработке!

= static partial class HelperFramework

> Namespace: Pixeye.Framework.HelperFramework

> Версия фреймворка: https://github.com/dimmpixeye/actors/tree/2019.9.15[2019.09.15] +
> Последнее обновление статьи: [2019.09.16]

## Описание
HelperFramework - вспомогательный класс фреймворка. В нем содержится множество методов расширений, которые облегчат вашу жизнь! :D Они могут быть разбросаны по разным файлам, поэтому, возможно, Вы встретите их и в других статьях.

> Методы расширения первым параметром содержит this. Для более подробной информации о методах расширения, обратитесь к справочнику языка C#.

---

> Файл HelperFramework.cs +
> Последнее изменение файла: [2019.02.24]

## Math

.Math
|===
|Тип |Метод |Описание

.2+|bool
a| [source,csharp] 
Every(this float step, float time)
.2+|Проверяет...

a| [source,csharp] 
Every(this int step, float time)

.2+|bool
a| [source,csharp] 
PlusCheck(ref this float arg0_pl, float val_pl, float clamp_pl = 1f)
.2+|Прибавляет и проверяет...

a| [source,csharp] 
PlusCheck(ref this int arg0_pl, int val_pl, int clamp_pl = 1)
|===